### ISSUE TITLE
New idea - Automated process won't stuck any connection error

### ISSUE THREAD

**Issue by ghost** [koltyakov/sp-download#12]
**Hello @koltyakov** 

I would like share to you a new idea which is simple add a new property to `downloadFile` function.
This new property `reconnectManually: boolean = true` which is allow reject the process if it has any connection error.
By default, everything like before, but you can set to false the `reconnectManually` property and it allows to reject the process and return the error for the main process. If some automated process call the `downloadFile` function this process won't stuck with in the connection error.

I attached the download.ts.txt file where I made this changes: [download.ts.txt](https://github.com/koltyakov/sp-download/files/5652470/download.ts.txt)

(The original file was this: [https://github.com/koltyakov/sp-download/blob/master/src/api/Download.ts](https://github.com/koltyakov/sp-download/blob/master/src/api/Download.ts))

I hope that idea can help fix this issue and you think it can be useful.

**Comment by koltyakov** [comment]
Hi @tothlevente,

Thanks for the idea! However, I'm not sure it would work.

I guess you're concerned about interactive user prompts? These won't appear in a production environment as should be locked with `process.env.NODE_ENV = "production"` ([details](https://github.com/koltyakov/node-sp-auth-config#production-runtime)).

**Comment by ghost** [comment]
Yes, that was what I thinking about. 
Sorry, this part of the documentation is missed my attention. 

Thank you to your answer! 👍

**Comment by koltyakov** [comment]
No problem! Thanks for using the libraries!
