### ISSUE TITLE
Response code 404 (Not Found)

### ISSUE THREAD

**Issue by bhavyabpt007** [koltyakov/sp-download#20]
```
const download = new Download.Download({
    clientId : "****",
    clientSecret: "****"
  });
  let filePathToDownload = encodeURI("https://blaze863.sharepoint.com/sites/dev/Shared%20Documents/Test.xlsx");
  let saveToPath = './download';
  download.downloadFile(filePathToDownload, saveToPath)
  .then((savedToPath) => {
    console.log(`${argv.url} has been downloaded to ${savedToPath}`);
  })
  .catch((error) => {
    console.log("check")
    console.log(error);
  })
```
for this piece of code im getting 404 error even though the url works normally in  browser checked the authentication logic using the same clientid and clientsecret im able to gnerate tokens 
tried decoding uri still the same error

**Comment by koltyakov** [comment]
Try not doing `encodeURI` for the path which you pass to `downloadFile` method.

**Comment by bhavyabpt007** [comment]
@koltyakov have tried that as well, for now I just ended up calling the rest api directly but was intrested what could cause this issue the only difference was
`https://${sites}/_api/web/GetFolderByServerRelativeUrl('Shared%20Documents')/Files('test.xlsx')/$value`
 the format used does sp-download also expect this format or the actual path that is displayed on spo

**Comment by koltyakov** [comment]
It ends up with calling this endpoint, resolving site and relative urls automatically:

```typescript
`${siteUrl}/_api/Web/GetFileByServerRelativeUrl(@FileServerRelativeUrl)/$value` +
  `?@FileServerRelativeUrl='${encodeURIComponent(spRelativeFilePath)}'`
```

Can you try without encoded space:

```typescript
const filePathToDownload = "https://blaze863.sharepoint.com/sites/dev/Shared Documents/Test.xlsx";
```

**Comment by bhavyabpt007** [comment]
Tried it still the same

**Comment by koltyakov** [comment]
Another thing to suggest is crafting the whole credentials object.

```typescript
import { Download } from 'sp-download';
import { AuthConfig } from 'node-sp-auth-config';

const filePathToDownload: string = 'https://***.sharepoint.com/sites/***/Shared Documents/Archive.zip';
const saveToPath: string = './download';

const authConfig = new AuthConfig({
  configPath: './config/private.json',
  encryptPassword: true,
  saveConfigOnDisk: true
});

(async () => {
  const context = await authConfig.getContext();
  const download = new Download(context.authOptions);

  const savedToPath = await download.downloadFile(filePathToDownload, saveToPath)
  console.log(`The file has been downloaded to ${savedToPath}`);
})()
  .catch(console.error);
```

https://github.com/koltyakov/sp-download/assets/7816483/8eeb79ca-9159-413b-b09a-9c483e209408

UPD: Also checked that " " and "%20" in paths both work.

**Comment by koltyakov** [comment]
Going to close it. Feel free to reopen.
