### ISSUE TITLE
Wrong url, can't get Web property

### ISSUE THREAD

**Issue by RezaErfani67** [koltyakov/sp-download#4]
running this, return error :"Wrong url, can't get Web property"

```javascript
const Download = require('sp-download').Download;

const authContext = {
    username: "testuser",
    password: "111111",
    domain: "mysite.com"

};

const download = new Download(authContext);

let filePathToDownload = 'http://mysite/Shared%20Documents/test1.txt';
let saveToPath = './Content';

download.downloadFile(filePathToDownload, saveToPath)
    .then(savedToPath => {
        console.log(`${argv.url} has been downloaded to ${savedToPath}`);
    })
    .catch(error => {
        console.log(error);
    });

```

**Comment by koltyakov** [comment]
Hey @RezaErfani67,

Travelling now. Will take a look after coming back home. 
Everything looks good in your code. Maybe try to decode doc’s url? Could you try with a space and not its html code?

Also, are able to auhtenticate to this site with this creds?
Anyway, I’ll take a look in a while.

**Comment by RezaErfani67** [comment]
i did continue with SharepointPlus  From [here ](https://aymkdn.github.io/SharepointPlus/)....thanks

**Comment by koltyakov** [comment]
Encoded/non-encoded URIs can be used both, works with both.
Wasn't able to reproduce in my environments (SPO, 2016, 2013), download works well all over the versions, environment, and auth scenarios.
Didn't get the answer if you were able authenticating your SharePoint tenant in general.

Going to close the issue.
