### ISSUE TITLE
Microsoft.Data.OData.ODataException

### ISSUE THREAD

**Issue by anfasci** [koltyakov/sp-download#5]
I got an error like this, when try to download file from share point.

400 - {"error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"Invalid JSON. Unexpected end of input reached while processing a JSON string value."}}}

**Comment by koltyakov** [comment]
Hi @anfasci,

Can you provide a sample to reproduce the error?

**Comment by anfasci** [comment]
router.use("/fileDownload/:filePath", async (req, res, next) => {
  var filePath = req.params.filePath;
  const cc = encodeURI('sites/test/Shared Documents/Test1/'+filePath);
  var url = "https://abc.sharepoint.com/_api/web/GetFileByServerRelativePath(@v)/$value?@v='"+cc
  const authContext = {
    clientId: appConstants.conf.AUD,
    clientSecret: appConstants.conf.CLIENT_SECRET,
    realm: appConstants.conf.TENANT_ID
  };
  const download = new Download(authContext);
  let saveToPath = './download';

  download.downloadFile(url, saveToPath)
    .then(savedToPath => {
      console.log(`${url} has been downloaded to ${savedToPath}`);
      res.send(true);
    })
    .catch(error => {
      console.log(error);
      res.send(false);
    });

});

router.use("/download/:filePath", async (req, res, next) => {
  var filePath = req.params.filePath;
  var filename = './download/' + filePath;

  res.download(filename, (err) => {
    if (err) {
      console.log(err);
    }
    fs.unlink(filename, (err) => {
      if (err) {
        console.log(err);
      }
      console.log('FILE [' + filename + '] REMOVED!');
    });
  });
});

**Comment by koltyakov** [comment]
You're providing an incorrect URL. Should be a URL to the document, but not the API endpoint. E.g. `https://contoso.sharepoint.com/sites/site/doclib/folder/file.pdf`.

**Comment by anfasci** [comment]
Ok. Thanks. Code is working fine after change.

**Comment by koltyakov** [comment]
Nice. Closing the issue.
