### ISSUE TITLE
Server relative urls must start with SPWeb.ServerRelativeUrl

### ISSUE THREAD

**Issue by GabrielGalatti** [koltyakov/sp-download#7]
I'm trying to download images from a shared directory, but when I open the image, it's empty. So I have opened the image with Visual Studio Code, and got this message : 

<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2147024809, System.ArgumentException</m:code><m:message xml:lang="pt-BR">Server relative urls must start with SPWeb.ServerRelativeUrl</m:message></m:error>

I change the url sometimes, using the sp api but I didn't have sucess. Could you help me please?

**Comment by koltyakov** [comment]
Hi @GabrielGalatti,
 
What mode do you use (CLI or as a library)? Please provide a code sample.

Also, are you sure that you provide the path to a document correctly? Many try using path to a page but not an actual file ref.

**Comment by GabrielGalatti** [comment]
When I opened in browser the url change, so I have replaced in code and worked. Sorry, and is it a way to return the name of the file when you download it?

**Comment by GabrielGalatti** [comment]
And thanks to answer fast!!
