### ISSUE TITLE
LogLevel can't be switched of

### ISSUE THREAD

**Issue by pierrejochem** [koltyakov/sp-download#9]
If I set the logLevel to LogLevel.Off. 

> const options: IDownloadOptions = { logLevel: LogLevel.Off };

I can still see messages in the console.

**Comment by koltyakov** [comment]
What version are you using? Please try the latest one, v.1.1.0.

**Comment by koltyakov** [comment]
Can you also provide a sample as I can't reproduce? Changing log level effects on logging and disabling logging works for me.

**Comment by koltyakov** [comment]
Seems I've found an issue, was able to reproduce.

**Comment by pierrejochem** [comment]
I see it. Thank you. Then I will delete my pull request.

**Comment by koltyakov** [comment]
Pushed the new version. `sp-download@1.1.1` Please try if it solves the issue.

![sp-download-log-level](https://user-images.githubusercontent.com/7816483/66905338-58b55d00-f00e-11e9-9e46-595182e3b4a4.gif)

**Comment by pierrejochem** [comment]
Works like a champ 👍

**Comment by koltyakov** [comment]
Cool, thanks!

**Comment by pierrejochem** [comment]
Thank you 🥇
